# Site settings
title: Nejvi
email: nejvib@gmail.com
description: Nejvi is an illustrator and fashion designer. This is her personal blog to showcase her writing and work.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "nejvib.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
# permalink: pretty
exclude: ["node_modules", "gulpfile.js", "package.json"]



collections:
  illustrations:
    output: true
    permalink: "/:path"

defaults:
  - scope:
      path: ""
      type: "illustrations"
    values:
      layout: "illustrations"


prose:
  rooturl: ""
  siteurl: "http://nejvib.github.io/"
  media: "assets/images"
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /_sass
    - /css
    - /js
    - /assets/fonts
    - .gitignore
    - gulpfile.js
    - package.json
  metadata:
    _illustrations:
      - name: "layout"
        field:
          element: "hidden"
          value: "illustrations"
